#This Class

class PlaneModel:
    def __init__(self, wing_area, fuselage_length,SW2,SW3,V2,V3):
        self.wing_area = wing_area  # in square feet
        self.fuselage_length = fuselage_length  # in feet
        self.SW2 = SW2  # in lbs
        self.SW3 = SW3  # in lbs
        self.V2 = V2  # in ft/s
        self.V3 = V3  # in ft/s

    def sensor_size(self):
        """
        Calculate the sensor size based on the maximum weight and given aspect ratio.
        
        :param SW2: Weight of the aircraft in lbs
        :return: Sensor length/diameter in square feet
        """
        aspect_ratio = 6  # Length to width ratio of the sensor
        Cd0 = 
        sensor_length = 
        return sensor_length

    def calculate_lift(self, air_density, velocity):
        """
        Calculate the lift force generated by the aircraft.
        
        :param air_density: Density of air in kg/m^3
        :param velocity: Velocity of the aircraft in m/s
        :return: Lift force in Newtons
        """
        lift = 0.5 * air_density * velocity**2 * self.wing_area * self.drag_coefficient
        return lift

    def calculate_drag(self, air_density, velocity):
        """
        Calculate the drag force experienced by the aircraft.
        
        :param air_density: Density of air in kg/m^3
        :param velocity: Velocity of the aircraft in m/s
        :return: Drag force in Newtons
        """
        drag = 0.5 * air_density * velocity**2 * self.wing_area * self.drag_coefficient
        return drag
